### PR TITLE
Warn when Python debugging library path is not found

### LINKED ISSUE #68: Python launcher should warn on unsupported Python version
We currently support Python 2.7 and 3.7+.  The Python launcher should fail when running with an unsupported version.  Currently the attempt to launch Python fails with a cryptic error like:
```
/usr/local/bin/python: No module named debugpy
```

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes #68

Emits a warning if the calculated Python library location does not exist.  We don't error as the user may have explicitly installed the debug library themselves.
```
WARN[0000] Debugging support for Python 3.2 not found: may require manually installing "pydevd" 
```

### CODE REVIEW

File: python/helper-image/launcher/launcher.go [hunk 1]
```diff
@@ -358,3 +364,11 @@ func logrusLevel(env env) logrus.Level {
 	}
 	return logrus.WarnLevel
 }
+
+func pathExists(path string) bool {
```
Comment (aaron-prindle) [inline python/helper-image/launcher/launcher.go:368]: Would it make sense to use os.path.exists? - https://docs.python.org/3/library/os.path.html#os.path.exists

**Review by aaron-prindle — APPROVED** [review]
LGTM

File: python/helper-image/launcher/launcher.go (hunk 1 above)
Comment (briandealwis) [reply python/helper-image/launcher/launcher.go:368]: I wish Go had something as simple 🙄
