### PR TITLE
Launch original app command-line should debugging configuration fail

### LINKED ISSUE #81: python debug helper should not exit on undebuggable situations
`skaffold debug` fails on the [_Bank of Anthos_](https://github.com/GoogleCloudPlatform/bank-of-anthos) as the python launcher sees the `uwsgi`:
```
[contacts-65fc7dc6bf-tndvr contacts] time="2021-06-02T05:23:00Z" level=fatal msg="error launching python debugging: unable to determine python version from \"uwsgi\": exit status 1"
```

And it fails in a similar fashion on [`HipsterShop`](https://github.com/GoogleCloudPlatform/microservices-demo):
```
 > [loadgenerator-cdfcccf64-zlw22 main] time="2021-06-02T05:28:03Z" level=fatal msg="error launching python debugging: unable to determine python version from \"/bin/bash\": exit status 2"
```

The python launcher should not be erroring out in this situation but should just execute the original command line.

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes #81 

Separate the debug-launching into a _preparation_ phase and _launching_ phase.  The preparation phase is responsible for transforming the application command-line into a debuggable launch command-line; the launching phase then invokes the resulting command-line.  If the preparation phase fails, then the python launcher just invokes the original application command-line.

This PR makes a few additional changes to better support this separation:
- It treats failure to determine Python version as a preparation error: if the binary doesn't support `-V` to report the python version, such as `uwsgi`, then it's unlikely to support other debug options.
- It propagates the exit code back to the container

It also adds some doc comments to describe the environment variables that allow tweaking behaviour.

cc: @peterlin741, @j-windsor

### CODE REVIEW

File: python/helper-image/launcher/launcher.go [hunk 1]
```diff
@@ -126,11 +146,16 @@ func main() {
 		logrus.Fatal("expected python command-line args")
 	}
 	pc.args = flag.Args()
-	logrus.Tracef("command-line: %v", pc.args)
+	logrus.Debug("app command-line: ", pc.args)
 
-	if err := pc.launch(ctx); err != nil {
-		logrus.Fatalf("error launching python debugging: %v", err)
+	if !pc.prepare(ctx) {
```
Comment (aaron-prindle) [inline python/helper-image/launcher/launcher.go:151]: Out of curiosity if prepare fails, why does it make sense to launch the original command vs being a fatal error?

File: python/helper-image/launcher/launcher.go [hunk 2]
```diff
@@ -64,10 +68,24 @@ limitations under the License.
 // python -m pydevd --server --port 5678 --DEBUG --continue \
 //   --file /tmp/pydevd716531212/skaffold_pydevd_launch.py
 // ```
+//
+// The launcher can be configured through several environment
+// variables:
```
Comment (aaron-prindle) [inline python/helper-image/launcher/launcher.go:73]: Is there a recommended way for skaffold users to configure the env vars of the helper image?  If so perhaps it would make sense add a blurb/doc-somwhere on how a skaffold user should set these.

File: python/helper-image/launcher/launcher.go [hunk 3]
```diff
@@ -252,6 +298,13 @@ func (pc *pythonContext) unwrapLauncher(_ context.Context) error {
 	return nil
 }
 
+func (pc *pythonContext) isPythonLauncher(ctx context.Context) error {
+	major, minor, err := determinePythonMajorMinor(ctx, pc.args[0], pc.env)
+	pc.major = major
```
Comment (aaron-prindle) [inline python/helper-image/launcher/launcher.go:303]: are all python versions supported?  I see - https://github.com/GoogleContainerTools/container-debug-support/issues/67
would it make sense to error if 3.4 or below is found?

File: python/helper-image/launcher/launcher.go (hunk 1 above)
Comment (briandealwis) [reply python/helper-image/launcher/launcher.go:151]: If we're unable to configure the app for debugging, then we just launch the original command without debugging.  Otherwise for microservices-type apps, the failure to debugify a container can lead to the app failing.

#81 includes pointers to failure cases with Bank of Anthos and Hipster Shop.

File: python/helper-image/launcher/launcher.go (hunk 2 above)
Comment (briandealwis) [reply python/helper-image/launcher/launcher.go:73]: Hoping that the users never need to do this.  But yes, it would be useful to document at least `WRAPPER_ENABLE`.

File: python/helper-image/launcher/launcher.go (hunk 3 above)
Comment (briandealwis) [reply python/helper-image/launcher/launcher.go:303]: I'm not sure it makes sense to hard-code it, especially since users can also put ptvsd or whatever into their requirements.txt.

Comment (briandealwis) [reply python/helper-image/launcher/launcher.go:303]: 3.4 was released in 2014, so it's unlikely to occur in practice 🤞

**Review by aaron-prindle — APPROVED** [review]
LGTM
